version: '2'

services:
  ap:
    container_name: robert-app
    depends_on:
      - mongodb
    image: localhost:5000/robert0714/google-place-mongo:1.0-SNAPSHOT
    volumes: 
      - $PWD/poi/conf/source/placeIds:/root/poi/conf/source/placeIds
      - $PWD/poi/output:/root/poi/output
    environment:
      - MONGO_URL=mongodb
      - TZ=Asia/Taipei
    ports: 
      - "8080:8080"    
  mongodb:
    container_name: robert-mongodb
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"    
    volumes:
      - $PWD/data/mongodb:/data/db
    environment:
      - MONGODB_DATABASE=ec
     
    